# version: '3.9'

# services:
#   app:
#     build: .
#     container_name: gestion_recette_api
#     env_file: .env
#     ports:
#       - "3308:3005" # Port d'accès de ton application
#     depends_on:
#       - db
#     environment:
#       DB_HOST: ${DB_HOST}
#       DB_USER: ${DB_USER}
#       DB_PASSWORD: ${DB_PASSWORD}
#       DB_NAME: ${DB_NAME}

#   db:
#     image: mysql
#     restart: always
#     container_name: gestion_recette_db
#     env_file: .env
#     volumes:
#       - db-config:/etc/mysql
#       - db-data:/var/lib/mysql
#     ports:
#       - "3307:3306" # Port de MySQL
#     environment:
#       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MYSQL_DATABASE: ${MYSQL_DATABASE}

# volumes:
#   db-config:
#   db-data:



version: '3.8'  # Supprimez la version si elle est obsolète, comme le suggère l'avertissement

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"

  app:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "3005:3005"
    depends_on:
      - db

volumes:
  db-data:
